### ISSUE TITLE
Unable to compile with Apportable

### ISSUE THREAD

**Issue by jjxtra** [cocos2d/cocos2d-objc#845]
I am unable to compile with Cocos2d 3.1 with Apportable 1.1.12. Here are some of the errors I've been getting:

CCRenderer.h:110:62: error: no member named 'y' in '_GLKVector2'
        float cshy = fmaxf(fabsf(extents.x_transform->m01 + extents.y_transform->m11), fabsf(extents.x_transform->m01 - extents.y_transform->m11));

CCRenderer.h:113:86: error: no member named 'm13' in '_GLKMatrix4'
        float w = fabs(csc.w) + fmaxf(fabsf(extents.x_transform->m03 + extents.y_transform->m13), fabsf(extents.x_transform->m03 - extents.y_transform->m13));

CCRenderer.h:113:86: error: no member named 'm13' in '_GLKMatrix4'
        float w = fabs(csc.w) + fmaxf(fabsf(extents.x_transform->m03 + extents.y_transform->m13), fabsf(extents.x_transform->m03 - extents.y_transform->m13));

Suggestions? Is there a project setting I need to change?

**Comment by slembcke** [comment]
GLKMath uses anonymous structs which are a GNU extension. Set your language dialect to gnu99 (I would guess it's c99 right now). The command line switch is `-std=gn99` if that is helpful to search for.

**Comment by jjxtra** [comment]
Thanks for responding. Unfortunately my language dialect was already gnu99 (-std=gnu99).

Are there any other settings to try? Do I need to make this change in the apportable project that was created?

**Comment by slembcke** [comment]
Possibly? Not sure why it doesn't "just work", I've never ran into an issue with that in particular, but I'm not an Apportable guru at all.

I remember this coming up recently, maybe that's helpful? https://code.google.com/p/apportable/issues/detail?id=798

**Comment by jjxtra** [comment]
Thanks for the link. Any idea when GLKit will be removed as a dependency?
